'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowRight, ArrowLeft, Check, Sparkles, LockKeyhole, RotateCcw, Globe2 } from 'lucide-react';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Progress } from '@/components/ui/progress';
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogClose } from '@/components/ui/dialog';
import { questions, recommendedPlan, validPhone } from './quiz-data';

type Screen = 'intro'|'quiz'|'contact'|'analysis'|'result';
export default function Home(){
 const [screen,setScreen]=useState<Screen>('intro');const [step,setStep]=useState(0);const [answers,setAnswers]=useState<string[]>(Array(5).fill(''));const [name,setName]=useState('');const [phone,setPhone]=useState('');const [email,setEmail]=useState('');const [error,setError]=useState('');const [analysisStage,setAnalysisStage]=useState(0);const [dialog,setDialog]=useState(false);const heading=useRef<HTMLHeadingElement>(null);
 const state=useRef({screen,step,answers});state.current={screen,step,answers};
 const online=recommendedPlan(answers)==='Cademy';const question=questions[step];
 useEffect(()=>{if(screen!=='intro')heading.current?.focus();window.scrollTo({top:0,behavior:'instant'});},[screen,step]);
 useEffect(()=>{if(screen!=='analysis')return;setAnalysisStage(0);const first=setTimeout(()=>setAnalysisStage(1),1250);const last=setTimeout(()=>setScreen('result'),2800);return()=>{clearTimeout(first);clearTimeout(last)}},[screen]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'start_body_plan_quiz',title:'Iniciar diagnóstico',description:'Abre a primeira pergunta do quiz sem enviar dados.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Não são aceites parâmetros.');setStep(0);setScreen('quiz');await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return{screen:state.current.screen,question:questions[0].title};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort()},[]);
 function choose(value:unknown){if(typeof value!=='string'||!question.options.includes(value))return;setAnswers(prev=>prev.map((a,i)=>i===step?value:a))}
 function next(){if(!answers[step])return;if(step===4)setScreen('contact');else setStep(step+1)}
 function back(){setError('');if(screen==='contact'){setStep(4);setScreen('quiz')}else if(step>0)setStep(step-1);else setScreen('intro')}
 function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!name.trim()){setError('Escreve o teu nome.');return}if(!validPhone(phone)){setError('Introduz um número de WhatsApp válido, com indicativo.');return}setError('');setScreen('analysis')}
 function restart(){setAnswers(Array(5).fill(''));setStep(0);setScreen('intro');setName('');setPhone('');setEmail('');setError('')}
 return <div className={`site screen-${screen}`}><header className="header"><a className="brand" href="/" aria-label="Bruno Samora, início"><span className="brand-mark">B<span>S</span></span><span>BRUNO<br/>SAMORA<span className="brand-dot">.</span></span></a>{screen==='intro'?<span className="header-mark" aria-hidden="true"><i/><i/><i/></span>:<span className="header-caption">O TEU PRÓXIMO PASSO</span>}</header>
 {screen==='intro'&&<><main className="hero enter"><section className="hero-copy"><h1>Qual é o melhor plano para <em>transformares</em> o teu corpo?</h1><p>Responde a 5 perguntas rápidas.</p><button className="primary" onClick={()=>setScreen('quiz')}>Fazer diagnóstico gratuito<ArrowRight size={21}/></button></section><figure className="hero-photo"><div className="photo-red"/><img src="/images/bruno.jpeg" alt="Bruno Samora numa pose de força" fetchPriority="high"/><span className="photo-outline" aria-hidden="true"/><span className="photo-arrow" aria-hidden="true"><ArrowUpRight/></span><span className="photo-sign" aria-hidden="true">Bruno Samora</span></figure></main><div className="hero-bottom" aria-hidden="true"><span className="mini-line"/><div className="step-dots"><b/><i/><i/><i/><i/></div><span className="mini-line"/></div></>}
 {(screen==='quiz'||screen==='contact')&&<main className="flow"><div className="flow-top"><button className="back" onClick={back}><ArrowLeft size={17}/>Voltar</button><span>{screen==='quiz'?`Pergunta ${String(step+1).padStart(2,'0')} de 05`:'Último passo'}</span></div><Progress value={screen==='contact'?100:(step+1)*20} aria-label="Progresso do diagnóstico" className="quiz-progress"/>
 {screen==='quiz'?<section key={step} className="question enter"><figure className="question-photo"><img src={`/images/${question.image}`} alt={question.alt}/><span className="image-corner" aria-hidden="true"><ArrowUpRight/></span><figcaption>Imagem criada por IA</figcaption></figure><div className="question-content"><span className="eyebrow">O TEU PONTO DE PARTIDA</span><h1 ref={heading} tabIndex={-1} id="question-heading">{question.title}</h1><RadioGroup aria-labelledby="question-heading" value={answers[step]} onValueChange={choose} className={`answer-grid ${step===0?'two-options':''}`}>{question.options.map((option,i)=><label key={option} className={`answer-card ${answers[step]===option?'selected':''}`}><span className="option-letter" aria-hidden="true">{String.fromCharCode(65+i)}</span><span>{option}</span><RadioGroupItem value={option} aria-label={option}/></label>)}</RadioGroup><button className="primary continue" disabled={!answers[step]} onClick={next}>Continuar<ArrowRight size={20}/></button></div></section>:<section className="contact enter"><span className="small-icon"><Sparkles size={25}/></span><span className="eyebrow">JÁ ESTÁS MAIS PERTO</span><h1 ref={heading} tabIndex={-1}>O teu plano começa <em>contigo.</em></h1><form onSubmit={submit}><label>Nome<input name="name" autoComplete="name" placeholder="Como te chamas?" required value={name} onChange={e=>setName(e.target.value)}/></label><label>WhatsApp<input name="tel" type="tel" inputMode="tel" autoComplete="tel" placeholder="+244 9XX XXX XXX" required value={phone} onChange={e=>setPhone(e.target.value)} aria-invalid={!!error} aria-describedby={error?'contact-error':undefined}/></label><label>E-mail <span className="optional">opcional</span><input name="email" type="email" autoComplete="email" placeholder="O teu e-mail" value={email} onChange={e=>setEmail(e.target.value)}/></label>{error&&<p id="contact-error" className="error" role="alert">{error}</p>}<button className="primary" type="submit">Ver o meu plano<ArrowRight size={20}/></button><p className="privacy"><LockKeyhole size={13}/>Neste protótipo, os dados não são enviados.</p></form></section>}
 </main>}
 {screen==='analysis'&&<main className="analysis enter" aria-live="polite"><div className="analysis-symbol"><Sparkles size={35}/></div><h1 ref={heading} tabIndex={-1}>A analisar as tuas respostas...</h1><p className={analysisStage?'analysis-active':''}>A escolher o melhor plano para ti...</p><Progress value={analysisStage?85:30} aria-label="Análise das respostas" className="analysis-progress"/></main>}
 {screen==='result'&&<main className="result enter"><div className="result-heading"><span className="result-check"><Check size={19}/></span><span className="eyebrow">O TEU PRÓXIMO PASSO ESTÁ AQUI</span></div><div className="result-grid"><section className="plan-card"><div className="plan-top"><span>Plano recomendado:</span>{online?<Globe2 size={25}/>:<span className="discount">30% OFF hoje</span>}</div><h1 ref={heading} tabIndex={-1}>{online?'Cademy':<>Plano<br/><em>Evolução</em></>}</h1>{online?<p className="plan-support online-support">Treina online com o método Bruno Samora.</p>:<><div className="price"><span className="old-price">De <s>357.000 Kz</s></span><span className="new-price"><span>Por</span> 249.999 <small>Kz</small></span></div><p className="plan-support">Ideal para começares com acompanhamento, método e evolução real.</p></>}<button className="primary" onClick={()=>setDialog(true)}>{online?'Entrar na lista Cademy':'Quero garantir o meu plano'}<ArrowUpRight size={21}/></button></section><figure className="result-photo"><img src="/images/bruno.jpeg" alt="Bruno Samora, treinador"/><span className="result-photo-name">BRUNO<br/>SAMORA<span>.</span></span></figure></div>{!online&&<div className="other-plans"><span>Outros planos</span><p>Plano Inicial <b>199.000 Kz</b></p><p>Plano Premium <b>449.999 Kz</b></p></div>}<button className="restart" onClick={restart}><RotateCcw size={15}/>Refazer diagnóstico</button></main>}
 <Dialog open={dialog} onOpenChange={setDialog}><DialogContent className="prototype-dialog" showCloseButton={false}><span className="small-icon"><Check size={25}/></span><DialogTitle>{online?'O teu próximo passo: Cademy':'O teu próximo passo: Plano Evolução'}</DialogTitle><DialogDescription>Esta é uma demonstração visual. Nenhuma reserva, inscrição ou pagamento foi efectuado.</DialogDescription><DialogClose className="primary">Voltar ao meu plano<ArrowRight size={18}/></DialogClose></DialogContent></Dialog>
 </div>
}
